include:
  - path: ./postgres/db.yaml
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoring

networks:
  monitoring:
    external: true